# Generated by Django 3.2.15 on 2023-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDocumentHit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(db_index=True, max_length=256)),
                ('doc_sha3_256', models.CharField(db_index=True, max_length=64)),
                ('doc_date_added', models.DateTimeField(db_index=True)),
            ],
            options={
                'unique_together': {('collection_name', 'doc_sha3_256')},
            },
        ),
    ]
