# Generated by Django 3.2.21 on 2023-09-13 00:08

from django.db import migrations, models
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.indexes.unique_index
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='CollectionDocumentHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(db_index=True, max_length=256)),
                ('doc_sha3_256', models.CharField(db_index=True, max_length=64)),
                ('doc_date_added', models.DateTimeField(db_index=True)),
            ],
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['HASH'],
                'key': ['doc_sha3_256'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='collectiondocumenthit',
            index=psqlextra.indexes.unique_index.UniqueIndex(fields=['doc_sha3_256', 'collection_name'], name='common_data_doc_sha_feb379_idx'),
        ),
    ]
