# Generated by Django 3.2.21 on 2023-09-13 13:12

from django.db import migrations, models
import snoop.data.collections


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0002_partition_collection_document_hit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextcloudCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('opt', models.JSONField(blank=True, null=True)),
            ],
            bases=(models.Model, snoop.data.collections.Collection),
        ),
    ]
