kind: pipeline
name: test

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

- name: build base docker image
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-snoop2
    # https://0-8-0.docs.drone.io/substitution/
    auto_tag: true
    auto_tag_suffix: base
    dockerfile: Dockerfile.base
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
    branch:
    - master

- name: download testdata
  image: alpine/git:1.0.7
  commands:
  - mkdir -p testsuite/volumes/collections
  - git clone https://github.com/hoover/testdata testsuite/volumes/collections/testdata
  #- chown 666:666 testsuite/volumes/collections/testdata


- name: do the docker setup
  image: docker/compose:1.24.0
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - cd testsuite
  - mkdir -p volumes/search-es/data
  - chmod 777 volumes/search-es/data
  #- docker-compose up -d --scale snoop=0
  - cd ..
  - docker build --tag test:test

  
#
# - name: py.test
#   image: docker/compose:1.24.0
#   volumes:
#   - name: dockersock
#     path: /var/run
#   commands:
#   #- cd testsuite
#   #- docker-compose run --rm snoop bash -c '/wait && py.test -vv'
#   - cd /opt/hoover/snoop
#   - docker build --tag test:test

services:
- name: docker daemon in docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

- name: snoop-rabbitmq
  image: rabbitmq:3.7.3

- name: snoop-tika
  image: logicalspark/docker-tikaserver

- name: search-es
  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  volumes:
  - name: search-es-v
    path: /usr/share/elasticsearch/data
  environment:
    discovery.type: single-node

- name: snoop-pg
  image: postgres:12.2
  environment:
    POSTGRES_USER: snoop
    POSTGRES_DATABASE: snoop
    POSTGRES_PASSWORD: snoop
  volumes:
  - name: snoop-pg-v
    path: /var/lib/postgresql/data


volumes:
- name: dockersock
  temp: {}
- name: snoop-pg-v
  host:
    path: /opt/node/volumes/snoop-pg/data
- name: search-es-v
  host:
    path: /opt/node/volumes/search-es/data

#---
# kind: pipeline
# name: publish to docker hub
#
# trigger:
#   status:
#   - success
#   event:
#   - push
#   - tag
#
# depends_on:
# - test
#
# steps:
# - name: docker push branch ${DRONE_COMMIT_BRANCH}
#   image: plugins/docker
#   settings:
#     repo: liquidinvestigations/hoover-snoop2
#     # https://0-8-0.docs.drone.io/substitution/
#     tags: ${DRONE_COMMIT_BRANCH}
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#   when:
#     event:
#     - push
#     branch:
#       exclude:
#       - dependabot/**
#
# - name: docker push autotag + latest
#   image: plugins/docker
#   settings:
#     repo: liquidinvestigations/hoover-snoop2
#     auto_tag: true
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#
# ---
# kind: secret
# name: docker_username
# get:
#   path: liquid/ci/drone.docker
#   name: username
#
# ---
# kind: secret
# name: docker_password
# get:
#   path: liquid/ci/drone.docker
#   name: password
