#!/bin/bash -ex
cd "$(dirname ${BASH_SOURCE[0]})"

drone exec --branch $(git branch --show-current) --event push --pipeline static-tests .drone.yml

docker build . --tag liquidinvestigations/hoover-snoop2:$(git branch --show-current)
cp .drone.yml .drone.yml.bak
sed -i 's/pull\: always/pull\: if-not-exists/g' .drone.yml.bak
sed -i "s/py\.test -vv/py\.test `echo $@`/g" .drone.yml.bak
time drone exec --trusted --branch $(git branch --show-current) --event push --pipeline test --timeout 2h0m0s .drone.yml.bak
rm .drone.yml.bak
