#!/bin/bash -ex

/wait

if [[ "$DJ_TRACKER_ENABLE" == "true" ]]; then
  export RELOAD=""
else
  export RELOAD="--reload"
fi

if [[ "$DEBUG" == "true" ]]; then
	    # --max-requests 1 \  # poor man's autoreload
	  exec gunicorn $RELOAD \
	    --access-logfile '-' \
	    --error-logfile '-' \
	    --log-level 'info' \
           --worker-class $GUNICORN_WORKER_CLASS \
           --workers $GUNICORN_WORKERS \
           --threads $GUNICORN_THREADS \
           --max-requests $GUNICORN_MAX_REQUESTS \
	    --keep-alive 60 \
	    --timeout 600 \
	 -b 0.0.0.0:8080 \
	snoop.wsgi:application
else
	exec gunicorn \
	    --error-logfile '-' \
           --worker-class $GUNICORN_WORKER_CLASS \
           --workers $GUNICORN_WORKERS \
           --threads $GUNICORN_THREADS \
           --max-requests $GUNICORN_MAX_REQUESTS \
	    --keep-alive 60 \
	  --timeout 600 \
	 -b 0.0.0.0:8080 \
	snoop.wsgi:application
fi
