#!/bin/bash -ex
cd "$(dirname ${BASH_SOURCE[0]})"

(
  cd docs
  docker build . --tag hoover-snoop2-docs
)


docker run --rm \
  -it \
  --name 'hoover-snoop2-docs-server' \
  -v $PWD:/app -w /app \
  -v $TMP/hoover-snoop2-docs:/app/site \
  -p 8000:8000 \
  hoover-snoop2-docs ./_serve-docs
