import os

from snoop.defaultsettings import *

#print(f'SNOOP_ES_URL: {SNOOP_ES_URL}')
print(f'SNOOP_COLLECTIONS_ELASTICSEARCH_URL: {SNOOP_COLLECTIONS_ELASTICSEARCH_URL}')
print(f'SETTINGS.SNOOP_COLLECTIONS_ELASTICSEARCH_URL: {settings.SNOOP_COLLECTIONS_ELASTICSEARCH_URL}')
SNOOP_TESTDATA = SNOOP_COLLECTION_ROOT + '/testdata'
assert os.path.isdir(SNOOP_TESTDATA)

CELERY_TASK_ALWAYS_EAGER = True
CELERY_EAGER_PROPAGATES_EXCEPTIONS = True
