# Generated by Django 2.0 on 2018-01-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='path',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
