# Generated by Django 2.0 on 2018-01-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_collection_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('sha3_256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('sha1', models.CharField(db_index=True, max_length=40)),
                ('md5', models.CharField(db_index=True, max_length=32)),
                ('magic', models.CharField(max_length=4096)),
                ('mime_type', models.CharField(max_length=1024)),
                ('mime_encoding', models.CharField(max_length=1024)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Blob')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ctime', models.DateTimeField()),
                ('mtime', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Blob')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=1024)),
                ('args', models.CharField(max_length=4096)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_started', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('worker', models.CharField(blank=True, max_length=4096)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Blob')),
            ],
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='path',
            new_name='root',
        ),
        migrations.AddField(
            model_name='collection',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Collection'),
        ),
        migrations.AddField(
            model_name='file',
            name='parent_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Directory'),
        ),
        migrations.AddField(
            model_name='directory',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Collection'),
        ),
        migrations.AddField(
            model_name='directory',
            name='container_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.File'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Directory'),
        ),
        migrations.AddField(
            model_name='digest',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Collection'),
        ),
        migrations.AddField(
            model_name='digest',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.Blob'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('func', 'args')},
        ),
        migrations.AlterUniqueTogether(
            name='digest',
            unique_together={('collection', 'blob')},
        ),
    ]
