# Generated by Django 2.0 on 2018-01-06 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180106_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prev_set', to='data.Task')),
                ('prev', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_set', to='data.Task')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='parent_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_file_set', to='data.Directory'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('parent_directory', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('prev', 'next', 'name')},
        ),
    ]
