# Generated by Django 2.0 on 2018-01-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180106_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='container_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='child_directory_set', to='data.File'),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('parent_directory', 'name')},
        ),
    ]
