# Generated by Django 2.0 on 2018-01-08 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180106_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digest',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
