# Generated by Django 2.0 on 2018-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180108_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='args',
            field=models.JSONField(),
        ),
    ]
