# Generated by Django 2.0 on 2018-01-08 18:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180108_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
