# Generated by Django 2.0 on 2018-01-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20180110_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='traceback',
            field=models.TextField(blank=True),
        ),
    ]
