# Generated by Django 2.0 on 2018-02-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20180130_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('original_hash', models.CharField(db_index=True, max_length=64)),
                ('ocr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                          to='data.Blob')),
            ],
        ),
        migrations.CreateModel(
            name='OcrSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('root', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='data.OcrSource'),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='+', to='data.Blob'),
        ),
        migrations.AlterUniqueTogether(
            name='ocrdocument',
            unique_together={('source', 'original_hash')},
        ),
    ]
