# Generated by Django 2.0 on 2018-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20180301_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='es_index',
            field=models.CharField(default='default', max_length=4096),
            preserve_default=False,
        ),
    ]
