# Generated by Django 2.0.4 on 2018-04-26 12:48

from django.db import migrations


def remove_walk_file_tasks(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Task = apps.get_model('data', 'Task')
    TaskDependency = apps.get_model('data', 'TaskDependency')
    deps = (
        TaskDependency.objects.using(db_alias)
        .filter(prev__func='filesystem.walk_file')
    )
    deps.delete()
    Task.objects.using(db_alias).filter(func='filesystem.walk_file').delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_remove_task_traceback'),
    ]

    operations = [
        migrations.RunPython(remove_walk_file_tasks, noop),
    ]
