# Generated by Django 2.0.4 on 2018-05-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20180426_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='collection',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='data.Collection'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='collection',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='data.Collection'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='container_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='child_directory_set', to='data.File'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='child_directory_set', to='data.Directory'),
        ),
        migrations.AlterField(
            model_name='file',
            name='collection',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='data.Collection'),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='child_file_set', to='data.Directory'),
        ),
    ]
