# Generated by Django 2.0.4 on 2018-05-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20180509_1344'),
    ]

    operations = [
        migrations.RunSQL(
            'UPDATE data_file SET blob_id = original_id WHERE blob_id IS NULL',
            'SELECT 1',
        ),
        migrations.AlterField(
            model_name='file',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Blob'),
        ),
    ]
