# Generated by Django 2.2.8 on 2020-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20200212_2027'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['date_finished'], name='data_task_date_fi_c937d4_idx'),
        ),
    ]
