# Generated by Django 3.0.4 on 2020-05-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20200219_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrsource',
            name='root',
        ),
    ]
