# Generated by Django 3.0.4 on 2020-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_remove_ocrsource_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrsource',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
