# Generated by Django 3.0.4 on 2020-05-21 22:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20200512_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
