# Generated by Django 3.1.4 on 2020-12-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=512)),
                ('public', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.digest')),
            ],
            options={
                'unique_together': {('digest', 'user', 'tag', 'public')},
            },
        ),
    ]
