# Generated by Django 3.1.4 on 2020-12-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_documentusertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='blob',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.blob'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='documentusertag',
            name='digest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.digest'),
        ),
        migrations.AlterField(
            model_name='file',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data.blob'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='ocr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data.blob'),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ocrsource'),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='task',
            name='blob_arg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.blob'),
        ),
    ]
