# Generated by Django 3.1.4 on 2021-01-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_auto_20201216_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentusertag',
            name='date_indexed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='documentusertag',
            index=models.Index(fields=['date_indexed'], name='data_docume_date_in_129dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentusertag',
            index=models.Index(fields=['date_indexed', 'user', 'digest'], name='data_docume_date_in_f16ec5_idx'),
        ),
    ]
