# Generated by Django 3.1.4 on 2021-01-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_auto_20210104_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'statistics'},
        ),
    ]
