# Generated by Django 3.1.4 on 2021-02-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20210105_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentusertag',
            name='uuid',
            field=models.CharField(default='invalid', max_length=256),
        ),
        migrations.AddIndex(
            model_name='documentusertag',
            index=models.Index(fields=['digest', 'tag', 'public', 'uuid', 'date_indexed'], name='data_docume_digest__0352a8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentusertag',
            index=models.Index(fields=['digest', 'public', 'tag', 'date_indexed'], name='data_docume_digest__0d1ebc_idx'),
        ),
    ]
