# Generated by Django 3.1.4 on 2021-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20210325_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
        migrations.AddField(
            model_name='task',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blob',
            name='size',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['func', 'date_started', 'date_finished'], name='data_task_func_1fdea3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['func', 'version'], name='data_task_func_0370da_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'fail_count'], name='data_task_status_5061c8_idx'),
        ),
    ]
