# Generated by Django 3.1.4 on 2021-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_pdfpreview'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['broken_reason'], name='data_task_broken__46ebc8_idx'),
        ),
    ]
