# Generated by Django 3.1.4 on 2022-02-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20220201_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.blob'),
        ),
    ]
