# Generated by Django 3.1.4 on 2022-02-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_auto_20220216_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=1024)),
                ('blacklisted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='digest',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='data.blob'),
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3)),
                ('engine', models.CharField(max_length=256)),
                ('model_name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'unique_together': {('language_code', 'engine', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='EntityHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_source', models.CharField(max_length=256)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.digest')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.entity')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.languagemodel')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.entitytype'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('entity', 'type')},
        ),
    ]
