# Generated by Django 3.1.4 on 2022-03-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_digest_extra_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_source_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='extra_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='digest_extra_result_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='digest_result_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='original_file_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ocr_document_text_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='pdfpreview',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_preview_original_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='pdfpreview',
            name='pdf_preview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pdf_preview_result_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='task',
            name='blob_arg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_arg_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_original_set', to='data.blob'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='thumbnail_result_set', to='data.blob'),
        ),
    ]
