# Generated by Django 3.1.4 on 2022-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_auto_20220310_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='collection_source_key',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
