# Generated by Django 3.1.4 on 2022-04-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_blob_collection_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='archive_source_blob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='archive_children_blobs', to='data.blob'),
        ),
        migrations.AddField(
            model_name='blob',
            name='archive_source_key',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
