# Generated by Django 3.1.4 on 2022-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_auto_20220402_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='archive_source_key',
            field=models.BinaryField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='blob',
            name='collection_source_key',
            field=models.BinaryField(blank=True, max_length=4096),
        ),
    ]
