# Generated by Django 3.2.15 on 2022-11-17 17:28

from django.db import migrations


def reset_unarchive_tasks(apps, schema_editor):
    from snoop.data.tasks import retry_tasks

    db_alias = schema_editor.connection.alias
    Task = apps.get_model('data', 'Task')
    Blob = apps.get_model('data', 'Blob')
    all_archive_tasks = Task.objects.using(db_alias).filter(
        blob_arg__in=Blob.objects.using(db_alias).archive_source_blob)
    retry_tasks(all_archive_tasks, reset_fail_count=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20220407_1740'),
    ]

    operations = [
        migrations.RunPython(reset_unarchive_tasks, noop),
        migrations.RemoveField(
            model_name='blob',
            name='archive_source_blob',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='archive_source_key',
        ),
    ]
