# Generated by Django 3.2.15 on 2022-11-17 17:28

from django.db import migrations
from django.utils import timezone

STATUS_PENDING = 'pending'


def reset_unarchive_tasks(apps, schema_editor):
    now = timezone.now()

    db_alias = schema_editor.connection.alias
    Task = apps.get_model('data', 'Task')
    Blob = apps.get_model('data', 'Blob')
    all_archive_tasks = Task.objects.using(db_alias).filter(
        blob_arg__in=Blob.objects.using(db_alias).filter(
            pk__in=Blob.objects.using(db_alias).values('archive_source_blob').distinct()
        )
    )

    all_archive_tasks.update(
        status=STATUS_PENDING,
        error='',
        broken_reason='',
        log='',
        date_modified=now,
        fail_count=0,
    )

    Blob.objects.using(db_alias).update(
        archive_source_blob=None,
        archive_source_key=b'',
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20220407_1740'),
    ]

    operations = [
        migrations.RunPython(reset_unarchive_tasks, noop),
    ]
