# Generated by Django 3.2.15 on 2023-07-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_remove_archive_mount_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextcloudCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('initialized', models.BooleanField(default=False)),
            ],
        ),
    ]
