# Generated by Django 3.2.15 on 2023-07-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_nextcloudcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextcloudcollection',
            name='password',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nextcloudcollection',
            name='url',
            field=models.CharField(default='test', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nextcloudcollection',
            name='user',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
