# Generated by Django 3.2.21 on 2023-09-15 16:52

from django.db import migrations

from psqlextra.backend.migrations.operations import PostgresAddHashPartition

TASK_PARTITION_COUNT = 24

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_create_new_partitioned_tasks_tables'),
    ]

    operations = [
        PostgresAddHashPartition(
            model_name="TaskPartitioned",
            name=f"pt_func_args_{i+1}_of_{TASK_PARTITION_COUNT}",
            modulus=TASK_PARTITION_COUNT,
            remainder=i,
        )
        for i in range(TASK_PARTITION_COUNT)
    ]
