# Generated by Django 3.2.21 on 2023-09-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_create_task_table_partitions'),
    ]

    operations = [
        # Create the constraint manually
        migrations.RunSQL(
            """
            ALTER TABLE data_taskdependencypartitioned
            ADD CONSTRAINT data_taskdependencypartitioned_fk_next
            FOREIGN KEY (next_func, next_args)
            REFERENCES data_taskpartitioned (func, args)
            ON DELETE CASCADE
            """,
            """
            ALTER TABLE data_taskdependencypartitioned
            DROP CONSTRAINT data_taskdependencypartitioned_fk_next
            """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE data_taskdependencypartitioned
            ADD CONSTRAINT data_taskdependencypartitioned_fk_prev
            FOREIGN KEY (prev_func, prev_args)
            REFERENCES data_taskpartitioned (func, args)
            ON DELETE CASCADE
            """,
            """
            ALTER TABLE data_taskdependencypartitioned
            DROP CONSTRAINT data_taskdependencypartitioned_fk_prev
            """,
        ),
    ]
