# Generated by Django 3.2.21 on 2023-09-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_task_partitioned_m2m_fk'),
    ]

    operations = [
        migrations.RunSQL(
            """
            """,
            """
            """,
        ),
    ]
