# Generated by Django 3.2.21 on 2023-09-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_task_table_into_task_partitioned'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO data_taskdependencypartitioned
                     ("id", "name", "prev_func", "prev_args", "next_func", "next_args")
            SELECT dep.id, dep.name, _prev.func, _prev.args, _next.func, _next.args
            FROM data_taskdependency dep
            JOIN data_task _prev ON _prev.id = dep.prev_id
            JOIN data_task _next ON _next.id = dep.next_id
            """,
            """
            INSERT INTO data_taskdependency
                     ("id", "name", "prev_id", "next_id")
            SELECT dep.id, dep.name, _prev.id, _next.id
            FROM data_taskdependencypartitioned dep
            JOIN data_taskpartitioned _prev ON _prev.func = dep.prev_func AND _prev.args = dep.prev_args
            JOIN data_taskpartitioned _next ON _next.func = dep.next_func AND _next.args = dep.next_args
            """,
        ),
    ]
