# Generated by Django 3.2.21 on 2023-09-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_copy_data_task_dependency_partitioned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDependency',
        ),
    ]
