# Generated by Django 3.2.21 on 2023-09-15 19:10

from django.db import migrations, models
import psqlextra.indexes.unique_index


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskPartitioned',
            new_name='Task',
        ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_func_0609f2_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_status_ad7925_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_date_fi_cee01f_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_func_2ed6ba_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_status_e9181f_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_func_f10cf0_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_broken__5a76f6_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_func_b62ce4_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_func_f72a50_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='task',
        #     name='data_taskpa_status_e0ae3a_idx',
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=psqlextra.indexes.unique_index.UniqueIndex(fields=['func', 'args'], name='data_task_func_c1d523_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['status'], name='data_task_status_ab742f_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['date_finished'], name='data_task_date_fi_c937d4_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['func', 'status'], name='data_task_func_7a9361_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['status', 'date_modified'], name='data_task_status_6689af_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['func', 'date_modified'], name='data_task_func_bd935b_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['broken_reason'], name='data_task_broken__46ebc8_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['func', 'date_started', 'date_finished'], name='data_task_func_1fdea3_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['func', 'version'], name='data_task_func_0370da_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='task',
        #     index=models.Index(fields=['status', 'fail_count'], name='data_task_status_5061c8_idx'),
        # ),
    ]
