#!/usr/bin/env python

from pathlib import Path

import mkdocs_gen_files

CODE_ROOT = "snoop"

for path in Path(CODE_ROOT).glob("**/*.py"):
    doc_path = Path("reference", path.relative_to(".")).with_suffix(".md")

    with mkdocs_gen_files.open(doc_path, "w") as f:
        ident = ".".join(path.relative_to(".").with_suffix("").parts)
        # print(ident)
        print("::: " + ident, file=f)
        # print("--- ", file=f)
        # print("\n" * 10, file=f)
        # print(f"Code listing for: `{path}`", file=f)
        # print("```python ", file=f)
        # with open(path, 'r') as py:
        #     print(py.read(), file=f)
        # print("```", file=f)
        # print("--- ", file=f)
        # print("page generated by `docs/gen.py`", file=f)
        # print('</span>', file=f)

    mkdocs_gen_files.set_edit_path(doc_path, Path('..', path))
